'''Default parameters for reconciliation engine.'''

from decimal import Decimal

DATE_TOLERANCE_DAYS = 2
FUZZY_THRESHOLD = 85
VALUE_TOLERANCE = Decimal('0.00')
MAX_FILE_SIZE_MB = 20
MAX_ROWS_WARNING = 20000
SUPPORTED_EXTENSIONS = ('.csv', '.xlsx')
PT_REQUIRED_COLUMNS = ('Data', 'Descrição', 'Valor')
APP_VERSION = '1.0.0'
LOW_DESCRIPTION_SCORE = 60
DUPLICATE_DESCRIPTION_SCORE = 95
MISSING_DAY_FALLBACK = 9999
DEFAULT_SLIDER_LOW = 0.0
DEFAULT_SLIDER_HIGH = 10000.0
DEFAULT_VALUE_LOW = DEFAULT_SLIDER_LOW
DEFAULT_VALUE_HIGH = DEFAULT_SLIDER_HIGH
