'''Conciliation reports with pt-BR export.'''

from src.reporting.details import (
    _build_detail_dict,
    _collect_all_detail,
    _matched_rows,
    _matched_side,
    _resolve_side_frame,
    _single_row_dict,
    _single_side_row,
    _single_side_rows,
)
from src.reporting.errors import (
    _clean_error_frame,
    _concat_error_frames,
    _error_detail_rows,
    _error_frame_rows,
    _normalize_error_frames,
)
from src.reporting.exceptions import _exceptions_frame, build_exceptions_csv
from src.reporting.formatting import _as_number, _as_text, _format_iso, _sort_number, format_brl
from src.reporting.headers import (
    _ERROR_HEADERS_PT,
    _LOG_HEADERS_PT,
    _REPORT_HEADERS,
    _STATUS_PT,
    _manual_label,
    _manual_lookup,
    _reason_label,
    _status_label,
)
from src.reporting.kpis import _empty_kpis, _safe_len, calc_kpis
from src.reporting.lookups import _extract_side, _lookup_field
from src.reporting.rule_log import (
    _collect_error_log_rows,
    _collect_match_log_rows,
    _error_log_row,
    _infer_error_code,
    _match_log_row,
    build_rule_log,
)
from src.reporting.snapshots import _infer_params, _params_snapshot, _snapshot_text
from src.reporting.workbook import (
    _kpi_labels,
    _log_display_values,
    _param_rows,
    _write_all_details,
    _write_detail,
    _write_errors,
    _write_kpi_block,
    _write_log,
    _write_param_block,
    _write_resumo,
    build_conciliation_workbook,
)

__all__ = [
    '_ERROR_HEADERS_PT',
    '_LOG_HEADERS_PT',
    '_REPORT_HEADERS',
    '_STATUS_PT',
    '_as_number',
    '_as_text',
    '_build_detail_dict',
    '_clean_error_frame',
    '_collect_all_detail',
    '_collect_error_log_rows',
    '_collect_match_log_rows',
    '_concat_error_frames',
    '_empty_kpis',
    '_error_detail_rows',
    '_error_frame_rows',
    '_error_log_row',
    '_exceptions_frame',
    '_extract_side',
    '_format_iso',
    '_infer_error_code',
    '_infer_params',
    '_kpi_labels',
    '_log_display_values',
    '_lookup_field',
    '_manual_label',
    '_manual_lookup',
    '_match_log_row',
    '_matched_rows',
    '_matched_side',
    '_normalize_error_frames',
    '_param_rows',
    '_params_snapshot',
    '_reason_label',
    '_resolve_side_frame',
    '_safe_len',
    '_single_row_dict',
    '_single_side_row',
    '_single_side_rows',
    '_snapshot_text',
    '_sort_number',
    '_status_label',
    '_write_all_details',
    '_write_detail',
    '_write_errors',
    '_write_kpi_block',
    '_write_log',
    '_write_param_block',
    '_write_resumo',
    'build_conciliation_workbook',
    'build_exceptions_csv',
    'build_rule_log',
    'calc_kpis',
    'format_brl',
]
